# Generated by Django 3.1 on 2020-08-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200816_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
