# Generated by Django 3.1 on 2020-08-16 01:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200816_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=jsonfield.fields.JSONField(default='test2'),
            preserve_default=False,
        ),
    ]
