# Generated by Django 3.1 on 2020-08-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
    ]
