# Generated by Django 3.1 on 2020-08-19 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200819_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
