# Generated by Django 3.1 on 2020-08-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='api.store'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.user'),
        ),
    ]
